import tensorflow as tf
from tensorflow.keras import *

input = Input(shape=(800, 800, 1))
x = layers.Conv2D(6, (3, 3), activation='sigmoid', padding='same')(input)
x = layers.BatchNormalization()(x)
# output shape: (800, 800, 6)
x = layers.MaxPooling2D((4, 4), padding='same')(x)
x = layers.BatchNormalization()(x)
# downsize to (200, 200, 6)
x = layers.Conv2D(12, (3, 3), activation='sigmoid', padding='same')(x)
x = layers.BatchNormalization()(x)
# output shape: (200, 200, 12)
x = layers.MaxPooling2D((4, 4), padding='same')(x)
x = layers.BatchNormalization()(x)
# downsize to (50, 50, 12)
x = layers.Conv2D(24, (3, 3), activation='sigmoid', padding='same')(x)
x = layers.BatchNormalization()(x)
# output shape: (50, 50, 24)
x = layers.MaxPooling2D((2, 2), padding='same')(x)
x = layers.BatchNormalization()(x)
# downsize to (25, 25, 24)
x = layers.Conv2D(48, (3, 3), activation='sigmoid', padding='same')(x)
x = layers.BatchNormalization()(x)
# output shape: (50, 50, 48)
x = layers.MaxPooling2D((2, 2), padding='same')(x)
x = layers.BatchNormalization()(x)
# downsize to (13, 13, 48)

x = layers.Flatten()(x)
# x = layers.Dense(4056, activation='relu')(x)
# x = layers.BatchNormalization()(x)
x = layers.Dense(1024, activation='sigmoid')(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(512, activation='sigmoid')(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(128, activation='sigmoid')(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(64, activation='sigmoid')(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(32, activation='relu')(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(1, activation='relu')(x)


output = activations.relu(x)
model = Model(inputs=input, outputs=output, name="SAR_SHIP_DETECTION")
